### PR TITLE
In order to correct dialogbox problem on xubuntu 16.04 (filereader, save config, etc.)

### PR DESCRIPTION
**Pull request by delcasso**

### CODE REVIEW

**Comment by arrow-** [comment]
This is a quick fix for #42. I still haven't got around testing the latest JUCE 4.2.X _(nor 4.3.0)_ which, I believe have resolved the issue (see comments on #42).
A simpler solution is applied by @ablot [here](https://github.com/ablot/plugin-GUI/commit/e4bcf65dbb445660c4e5f665ff0857f3ccacb90e), by just adding a compile flag that disables native dialog boxes completely.

**Comment by aacuevas** [comment]
Is this issue still present in the development branch of the GUI? We updated its Juce version a bit ago but it still hasn't made the jump to the master branch.

**Comment by delcasso** [comment]
Yes !

**Comment by arrow-** [comment]
Ok, I dug into JUCE history.
@aacuevas The upstream patch was added on May 21, 2016 (on JUCE develop branch). So I expect JUCE 4.2.3+ to have the patch.
And (I think) we are on JUCE 4.2.1, see 3f5f403bfe484d1a5e043bb320ca24e6c938e186

**Comment by delcasso** [comment]
@aacuevas Sorry for the brief answer. I tested the development branch and that was still the case.
I you need I could make more tests.

**Comment by aacuevas** [comment]
It shouldn't be too hard to update JUCE to 4.2.3. In the meanwhile, this patch is still useful.
I just have two concerns I'd need to ask before merging:
-Since the proposed patch just disables the native file chooser for all linux builds, but the bug seems specific to xubuntu, and unaffected users might prefer their native dialogs, perhaps it would be better to follow @ablot's solution linked by @arrow-, since compiler flags are easy to modify.
-Usually patches go to the development branch, but this seems an important enough fix to go directly to the master branch. Our policies on this kind of things are kinda new so I'll have to check.

It seems I cannot reopen the pull request, but once those topics are talked about I'll implement one of the versions of this fix, until we can update Juce.

**Comment by delcasso** [comment]
Hi Aaron,

I modified the compiler flags in the makefile, it's cleaner. We should 
probably update the linux-installation-procedure with a link to another 
Makefile (for xubuntu and gentoo).

We could also generate binaries for xubuntu.

Sebastien

I you need I can remoake my changes on my for and creates a pull request

**Pull request closed without merging**
