### PR TITLE
Add Visual Studio 2015 support

### PR DESCRIPTION
**Pull request by galenlynch**
As it stands, I cannot compile the GUI using Visual Studio 2015 (#83). It looks like the Visual Studio solution and project file are generated by ProJucer? With these commits, I have updated the ProJucer file, and added the requisite resource to compile the main GUI program using Visual Studio 2015.

This is still not a complete fix to #83, because I don't know how to compile the plugins with Visual Studio 2015. The project files for each plugin also seem auto-generated by ProJucer, but I can't find the ProJucer file that generated them.

### CODE REVIEW

**Comment by galenlynch** [comment]
Is this pull request not going to be merged? I'm happy to close it if you have some reason for not wanting to integrate the changes.

**Comment by jsiegle** [comment]
@aacuevas can you take a look at? I don't think there's any reason not to merge it.

**Comment by aacuevas** [comment]
Oh, I missed this one. No, there is no big reason not to merge this. However, Galen, could you please create the appropriate VS2015 project files for the plugins? I don't have 2015 installed right now and, since the plugins need to be built with the same compiler as the base GUI, ideally we should ship projects for them as well.

**Comment by galenlynch** [comment]
Sure thing! I'll only be able to do it early next week, however.

**Pull request closed without merging**
